# Generated by Django 4.2.6 on 2023-10-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_superadmin_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='is_superuser',
        ),
    ]
