# Generated by Django 4.2.6 on 2023-10-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
