# Generated by Django 4.2.6 on 2023-10-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0005_remove_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_expire_time',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_secret',
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_create_branch',
            field=models.BooleanField(default=False),
        ),
    ]
