# Generated by Django 4.2.6 on 2023-10-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0006_remove_customuser_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_branch_admin',
            field=models.BooleanField(default=False),
        ),
    ]
