# Generated by Django 4.2.6 on 2023-10-10 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='branch_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='has_branch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='parent_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='business.business'),
        ),
    ]
