# Generated by Django 4.2.6 on 2023-10-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_business_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='universalentities',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='universalentities',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='universalentities',
            name='xbusiness',
        ),
        migrations.RemoveField(
            model_name='universalentities',
            name='xtype',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='UniversalEntities',
        ),
    ]
