# Generated by Django 4.2.6 on 2023-10-10 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0002_business_branch_num_business_has_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xname', models.CharField(max_length=100)),
                ('xdescription', models.TextField(blank=True)),
                ('xcode', models.CharField(blank=True, max_length=20)),
                ('xlatitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('xlongitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('status', models.BooleanField(default=True)),
                ('xcreated_at', models.DateTimeField(auto_now_add=True)),
                ('xupdated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('xbusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('xtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.type')),
            ],
            options={
                'unique_together': {('xtype', 'xname')},
            },
        ),
        migrations.DeleteModel(
            name='AccessCode',
        ),
        migrations.RemoveField(
            model_name='page',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Button',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
