# Generated by Django 4.2.6 on 2023-10-19 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeesDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=50, unique=True)),
                ('discount_code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], max_length=20)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fine_type', models.CharField(blank=True, choices=[(None, 'None'), ('Percentage', 'Percentage'), ('Fixed', 'Fixed')], default=None, max_length=20, null=True)),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fine_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('class_association', models.ManyToManyField(related_name='fees_masters', to='student.class')),
                ('fees_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.feesgroup')),
            ],
        ),
        migrations.CreateModel(
            name='FeesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('fee_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.CharField(blank=True, max_length=3, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=10)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fees_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.feesmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'unique_together': {('section_name',)},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disable', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=100, unique=True)),
                ('subject_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], max_length=20)),
            ],
            options={
                'unique_together': {('subject_name', 'subject_code')},
            },
        ),
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('student', models.ManyToManyField(related_name='categories', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('previous_school', models.CharField(max_length=150)),
                ('admission_status', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('guardian_contact_number', models.CharField(max_length=15)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.class')),
                ('fees_categories', models.ManyToManyField(blank=True, related_name='admissions', to='student.feesmaster')),
                ('section_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.section')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='admission_history',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student.studentadmission'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_payments',
            field=models.ManyToManyField(blank=True, related_name='studentpayment', to='student.payment'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('reminder_date', models.DateField()),
                ('reminder_message', models.TextField()),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='student.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='feesmaster',
            name='fees_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.feestype'),
        ),
        migrations.CreateModel(
            name='FeesCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('DD', 'DD'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('UPI', 'UPI'), ('Card', 'Card')], max_length=20)),
                ('collect_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.feesdiscount')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.payment')),
            ],
        ),
        migrations.CreateModel(
            name='DisableReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_name', models.CharField(max_length=50)),
                ('student', models.ManyToManyField(related_name='disable_reasons', to='student.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='sections',
            field=models.ManyToManyField(related_name='classes', to='student.section'),
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='classes', to='student.subject'),
        ),
        migrations.CreateModel(
            name='PromoteStudents',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField()),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_class', to='student.class')),
                ('from_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_section', to='student.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_class', to='student.class')),
                ('to_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_section', to='student.section')),
            ],
            options={
                'indexes': [models.Index(fields=['from_class'], name='student_pro_from_cl_09b9cf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='promotestudents',
            constraint=models.UniqueConstraint(fields=('from_class', 'promotion_id'), name='unique_promote_from_class_promotion_id'),
        ),
    ]
