# Generated by Django 4.2.6 on 2023-10-16 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('previous_school', models.CharField(max_length=150)),
                ('admission_year', models.CharField(max_length=4)),
                ('admission_status', models.CharField(max_length=50)),
                ('admission_type', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('guardian_contact_number', models.CharField(max_length=15)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.class')),
                ('section_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.section')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student.studentadmission')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.class')),
                ('current_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='student.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='sections',
            field=models.ManyToManyField(related_name='classes', to='student.section'),
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='classes', to='student.subject'),
        ),
        migrations.CreateModel(
            name='PromoteStudents',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField()),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_class', to='student.class')),
                ('from_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_section', to='student.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_class', to='student.class')),
                ('to_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_section', to='student.section')),
            ],
            options={
                'indexes': [models.Index(fields=['from_class'], name='student_pro_from_cl_09b9cf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='promotestudents',
            constraint=models.UniqueConstraint(fields=('from_class', 'promotion_id'), name='unique_promote_from_class_promotion_id'),
        ),
    ]
