# Generated by Django 4.2.6 on 2023-10-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission',
            new_name='admission_history',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='admission_type',
        ),
    ]
