# Generated by Django 4.2.6 on 2023-10-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_admission_student_admission_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentadmission',
            name='admission_year',
        ),
    ]
