# Generated by Django 4.2.6 on 2023-10-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
