# Generated by Django 4.2.6 on 2023-10-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_class_class_name_alter_section_section_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('student', models.ManyToManyField(related_name='categories', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='DisableReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_name', models.CharField(max_length=50, unique=True)),
                ('student', models.ManyToManyField(related_name='disable_reasons', to='student.student')),
            ],
        ),
    ]
