# Generated by Django 4.2.6 on 2023-10-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_status_student_is_disable_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disablereason',
            unique_together={('disable_name', 'id')},
        ),
    ]
