# Generated by Django 4.2.6 on 2023-10-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_paymentreminder_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feescollect',
            name='payment',
        ),
        migrations.AddField(
            model_name='feescollect',
            name='payment',
            field=models.ManyToManyField(related_name='fees_collects', to='student.payment'),
        ),
    ]
