# Generated by Django 4.2.6 on 2023-10-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_feescollect_payment_feescollect_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
