# Generated by Django 4.2.6 on 2023-10-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_feesdiscount_feesgroup_feestype_payment_feesmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesdiscount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feesgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feestype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
