# Generated by Django 4.2.6 on 2023-10-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_payment_balance_alter_payment_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
