# Generated by Django 4.2.6 on 2023-10-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_feesdiscount_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestype',
            name='fee_code',
            field=models.CharField(max_length=50),
        ),
    ]
