# Generated by Django 4.2.6 on 2023-10-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_feestype_fee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesdiscount',
            name='discount_code',
            field=models.CharField(max_length=50),
        ),
    ]
