# Generated by Django 4.2.6 on 2023-10-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_feescollect_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesmaster',
            name='fined',
            field=models.BooleanField(default=False),
        ),
    ]
