# Generated by Django 4.2.6 on 2023-10-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_feesdiscount_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('reminder_date', models.DateField()),
                ('reminder_message', models.TextField()),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.payment')),
            ],
        ),
    ]
