# Generated by Django 4.2.6 on 2023-10-17 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_paymentreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesmaster',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
