# Generated by Django 4.2.6 on 2023-10-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_feesmaster_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesdiscount',
            name='discount_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feesdiscount',
            name='discount_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feesgroup',
            name='group_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feestype',
            name='fee_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feestype',
            name='type_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
