# Generated by Django 4.2.6 on 2023-10-23 04:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_student_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Session name must be in the format "YYYY-YY" (e.g., 2019-20).', regex='^\\d{4}-\\d{2}$')])),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.session'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='session_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.session'),
        ),
    ]
