# Generated by Django 4.2.6 on 2023-10-23 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_session_student_current_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('date_from', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('room_no', models.CharField(max_length=20)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject', models.ManyToManyField(to='student.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarksDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=50)),
                ('percent_from', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_upto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MarksGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=10)),
                ('percent_upto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_from', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('no_of_exam', models.IntegerField()),
                ('exam', models.ManyToManyField(to='student.exam')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='AdmitCardDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('exam_center', models.CharField(max_length=100)),
                ('footer_text', models.TextField()),
                ('left_logo', models.ImageField(upload_to='admit_card_logos/')),
                ('right_logo', models.ImageField(upload_to='admit_card_logos/')),
                ('sign', models.ImageField(upload_to='admit_card_signs/')),
                ('background_image', models.ImageField(upload_to='admit_card_backgrounds')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
