# Generated by Django 4.2.6 on 2023-10-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_exam_examtype_marksdivision_marksgrade_examgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examgroup',
            name='no_of_exam',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='marksgrade',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
