# Generated by Django 4.2.6 on 2023-10-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_examgroup_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examgroup',
            name='no_of_exam',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
