# Generated by Django 4.2.6 on 2023-10-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_alter_admitcarddesign_exam_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admitcarddesign',
            old_name='exam_name',
            new_name='exam',
        ),
    ]
