# Generated by Django 4.2.6 on 2023-10-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_rename_exam_name_admitcarddesign_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksheetDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('exam_center', models.CharField(max_length=100)),
                ('footer_text', models.TextField()),
                ('body_text', models.TextField()),
                ('header_image', models.ImageField(upload_to='mark_sheet_header/')),
                ('left_logo', models.ImageField(upload_to='mark_sheet_logos/')),
                ('right_logo', models.ImageField(upload_to='mark_sheet_logos/')),
                ('left_sign', models.ImageField(upload_to='mark_sheet_signs/')),
                ('middle_sign', models.ImageField(upload_to='mark_sheet_signs/')),
                ('right_sign', models.ImageField(upload_to='mark_sheet_signs/')),
                ('background_image', models.ImageField(upload_to='mark_sheet_backgrounds')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
